version: 2
updates:
  # main branch
  - package-ecosystem: "nuget"
    directories:
      - "/*"
      - "/rebirth/*"
    target-branch: "main"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directories:
      - "/*"
      - "/rebirth/*"
    target-branch: "main"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  # main.v1 branch
  - package-ecosystem: "nuget"
    directories:
      - "/*"
      - "/rebirth/*"
    target-branch: "main.v1"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directories:
      - "/*"
      - "/rebirth/*"
    target-branch: "main.v1"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
