version: 2
updates:
  # main branch
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"

  # main.v1 branch
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "main.v1"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main.v1"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "main.v1"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main.v1"
    schedule:
      interval: "weekly"
