version: 2
updates:
  # main branch
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directories:
      - "/*"
      - "/rebirth/*"
    target-branch: "main"
    schedule:
      interval: "daily"

  # main.v1 branch
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: "main.v1"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directories:
      - "/*"
      - "/rebirth/*"
    target-branch: "main.v1"
    schedule:
      interval: "daily"
